### ISSUE TITLE
需要增加Gcoin白皮書連結

### ISSUE THREAD

**Issue by hanky312** [OpenNetworking/gcoinwebsite#1]
白皮書連結暫定
https://github.com/OpenNetworking/gcoin-community/blob/develop/README.md
位置建議如下圖兩個地方
![5dbc2493cac262d7495f2a95b7abc453](https://cloud.githubusercontent.com/assets/10375425/15773496/bd94d9f0-29a9-11e6-9350-4252087edd81.png)

**Comment by zhouer** [comment]
Fixed in ac84358
